version: '3.4'

services:
  postgresql:
    image: postgres
    container_name: bunker
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=bunker
      - POSTGRES_PASSWORD=bunker
      - POSTGRES_DATABASE=bunker
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-bunker
    ports:
      - '6379-6379'